/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beeple_bmesdk_BmeSdk */

#ifndef _Included_com_beeple_bmesdk_BmeSdk
#define _Included_com_beeple_bmesdk_BmeSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_beeple_bmesdk_BmeSdk
 * Method:    generateSound
 * Signature: ([BF[BFFI)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_beeple_bmesdk_BmeSdk_generateSound
  (JNIEnv *, jclass, jbyteArray, jfloat, jbyteArray, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
